# Generated by Django 5.1.6 on 2025-02-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='managers',
            field=models.ManyToManyField(related_name='managed_stores', to='users.customuser'),
        ),
    ]
