# Generated by Django 5.1.6 on 2025-02-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_rename_zip_code_store_plz_alter_store_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='state',
            new_name='_state',
        ),
        migrations.AddField(
            model_name='store',
            name='open_days',
            field=models.JSONField(default=list),
        ),
    ]
