# Generated by Django 5.1.6 on 2025-02-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_rename_state_store__state_store_open_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='open_days',
        ),
    ]
