# Generated by Django 5.1.6 on 2025-02-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_remove_store_open_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='_state',
            new_name='state',
        ),
    ]
