# Generated by Django 5.1.6 on 2025-02-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_rename__state_store_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='state',
            new_name='state_abbrv',
        ),
    ]
