# Generated by Django 5.1.6 on 2025-02-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_store_open_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mo', 'Montag'), ('Di', 'Dienstag'), ('Mi', 'Mittwoch'), ('Do', 'Donnerstag'), ('Fr', 'Freitag'), ('Sa', 'Samstag'), ('So', 'Sonntag')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='open_days',
        ),
        migrations.AddField(
            model_name='store',
            name='open_days',
            field=models.ManyToManyField(blank=True, related_name='stores', to='stores.day'),
        ),
    ]
