# Generated by Django 5.1.6 on 2025-02-19 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_alter_day_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='day',
            new_name='abbrv',
        ),
    ]
