# Generated by Django 5.1.6 on 2025-02-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_rename_day_day_abbrv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='open_days',
        ),
        migrations.AddField(
            model_name='store',
            name='dienstag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='donnerstag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='freitag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='mittwoch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='montag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='samstag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='sonntag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='abbrv',
            field=models.CharField(choices=[('mo', 'montag'), ('di', 'dienstag'), ('mi', 'mittwoch'), ('do', 'donnerstag'), ('fr', 'freitag'), ('sa', 'samstag'), ('so', 'sonntag')], max_length=2, unique=True),
        ),
    ]
