# Generated by Django 5.1.6 on 2025-02-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_remove_store_open_days_store_dienstag_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
