# Generated by Django 5.1.6 on 2025-02-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_delete_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='managers',
            new_name='manager_ids',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
