# Generated by Django 5.1.6 on 2025-02-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_alter_store_closing_time_alter_store_opening_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='plz',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
