# Generated by Django 5.1.6 on 2025-02-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_alter_store_plz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['id']},
        ),
    ]
