# Generated by Django 5.1.6 on 2025-02-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_alter_store_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='plz',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
