# Generated by Django 5.1.6 on 2025-03-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_alter_store_plz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
