# Generated by Django 5.1.6 on 2025-02-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_owner',
        ),
    ]
